# docker compose
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .dbenv
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
